export default function SysexKnobsUpdate(props){
	const {data, dispatch, expression} = props
	const updatedValues = data.slice(5, 22)
	dispatch({skipMidi: true, key: 9, value: updatedValues[13]})
	dispatch({skipMidi: true, key: 14, value: updatedValues[12]})
	dispatch({skipMidi: true, key: 15, value: updatedValues[16]})
	dispatch({skipMidi: true, key: 16, value: updatedValues[0]})
	dispatch({skipMidi: true, key: 17, value: updatedValues[1]})
	dispatch({skipMidi: true, key: 18, value: updatedValues[2]})
	dispatch({skipMidi: true, key: 19, value: updatedValues[3]})
	dispatch({skipMidi: true, key: 20, value: updatedValues[4]})
	dispatch({skipMidi: true, key: 21, value: updatedValues[5]})
	dispatch({skipMidi: true, key: 22, value: updatedValues[6]})
	dispatch({skipMidi: true, key: 23, value: updatedValues[7]})
	dispatch({skipMidi: true, key: 24, value: updatedValues[8]})
	dispatch({skipMidi: true, key: 25, value: updatedValues[9]})
	dispatch({skipMidi: true, key: 26, value: updatedValues[10]})
	dispatch({skipMidi: true, key: 27, value: updatedValues[11]})
	dispatch({skipMidi: true, key: 29, value: updatedValues[14]})
	dispatch({skipMidi: true, key: 30, value: updatedValues[15]})
}